services:
 app:
  image: ${IMAGE_NAME}
  container_name: ${IMAGE_NAME}
  build:
   context: .
   dockerfile: Dockerfile
   args:
    NODE_ENV: development
  working_dir: /app
  volumes:
   - ./src:/app/src
   - /app/node_modules
  env_file:
   - .env
  ports:
   - "${HOST_PORT}:${CONTAINER_PORT}"
  command: npm run docker-dev
