services:
 app:
  build:
   context: .
   dockerfile: dockerfile # Stelle sicher, dass der Dateiname korrekt ist
  working_dir: /app
  volumes:
   - .:/app:ro # :ro macht das Volumen schreibgeschützt, falls nur zum Lesen nötig
  environment:
   - NODE_ENV=production
  command: ["node", "index.js"]
